/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Models.CNAEAbstractTableModel;
import Auxiliares.GerenciaJFrames;
import Auxiliares.ManipulaComponentes;
import Configuracoes.DAO;
import Entidades.CNAE;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.beansbinding.ELProperty;

/**
 *
 * @author Joanes Gonzaga
 */
public final class frmCadastrarCNAE extends javax.swing.JDialog {

    ManipulaComponentes.statusCadastro statusFrame;
    ArrayList<JButton> botoes;
    ResultSet rs = null;
    CNAEAbstractTableModel model;
    List cnaeLista;
    int linhaParaEdicao;

    //Boolean statusCadastro;
    /**
     * Creates new form frmCadastrarCNAE
     */
    public frmCadastrarCNAE(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        botoes = new ArrayList<>();
        botoes.add(btnAdd);
        botoes.add(btnEdit);
        botoes.add(btnRemove);
        //botoes.add(btnSearch);
        botoes.add(btnDispose);

        cnaeLista = new ArrayList();
        model = new CNAEAbstractTableModel(cnaeLista);
        
        

        jTable1.setModel(model);

        carregaTabelaCNAEs();
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(450);

        statusFrame = ManipulaComponentes.statusCadastro.Navegando;

        Auxiliares.GerenciaJFrames.posicionaJDialogs(this);
        setTitle(getTitle() + " - " + statusFrame);
        
       //Binding b = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ, jTable1, ELProperty.create("${selectedElement.cnae}"), txtCNAECod,BeanProperty.create("text"));
      // b.bind();
        
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                int index100 = jTable1.getSelectedRow();
                if(statusFrame == statusFrame.Adicionando || statusFrame == statusFrame.Editando){
                    jTable1.setRowSelectionInterval(linhaParaEdicao, linhaParaEdicao);
            return;
        }
                
        txtCNAECod.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
        txtCNAEDesc.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());              
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        txtCNAECod = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCNAEDesc = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnDispose = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de CNAE");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Código CNAE:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(20, 5, 5, 5);
        getContentPane().add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.insets = new java.awt.Insets(20, 5, 5, 5);
        getContentPane().add(txtCNAECod, gridBagConstraints);

        jLabel2.setText("Descrição CNAE:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(txtCNAEDesc, gridBagConstraints);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder()));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        btnAdd.setText("Adicionar");
        btnAdd.setPreferredSize(new java.awt.Dimension(75, 23));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(btnAdd, gridBagConstraints);

        btnEdit.setText("Editar");
        btnEdit.setPreferredSize(new java.awt.Dimension(75, 23));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(btnEdit, gridBagConstraints);

        btnRemove.setText("Excluir");
        btnRemove.setPreferredSize(new java.awt.Dimension(75, 23));
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(btnRemove, gridBagConstraints);

        btnDispose.setText("Sair");
        btnDispose.setPreferredSize(new java.awt.Dimension(75, 23));
        btnDispose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisposeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(btnDispose, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setRowHeight(20);
        jScrollPane1.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 0, 0);
        jPanel2.add(jScrollPane1, gridBagConstraints);

        jLabel3.setText("jLabel3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel2.add(jLabel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        getContentPane().add(jPanel2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDisposeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisposeActionPerformed
        dispose();
    }//GEN-LAST:event_btnDisposeActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        
        if (statusFrame == ManipulaComponentes.statusCadastro.Navegando) {

            statusFrame = ManipulaComponentes.statusCadastro.Adicionando;
            ManipulaComponentes.gerenciaBotoes(botoes, statusFrame);
            setTitle("Cadastro de CNAE - " + statusFrame);
            txtCNAECod.setText(null);
            txtCNAEDesc.setText(null);
            txtCNAECod.requestFocus();
        } else if (statusFrame == ManipulaComponentes.statusCadastro.Adicionando) {

            if (txtCNAECod.getText().trim().equals("") || txtCNAEDesc.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Todos os Campos Precisam Estar Preenchidos!");
                return;
            } else {
                try {
                    Connection con = DAO.getConexao();
                    Integer codCNAE = Integer.parseInt(txtCNAECod.getText());
                    String descCNAE = txtCNAEDesc.getText();

                    String strSQL = "INSERT INTO cnae(codigo,descCNAE) VALUES(?,?)";
                    PreparedStatement pstm = con.prepareStatement(strSQL);
                    pstm.setInt(1, codCNAE);
                    pstm.setString(2, descCNAE);

                    int retorno = pstm.executeUpdate();
                    if (retorno <= 0) {
                        JOptionPane.showMessageDialog(null, "ATENÇÃO! Nenhum Registro Foi Incluído!");
                        return;
                    } else {
                        JOptionPane.showMessageDialog(null, "CNAE Incluído Com Sucesso!!");
                        
                        ManipulaComponentes.gerenciaBotoes(botoes, statusFrame = statusFrame.Navegando);
                        carregaTabelaCNAEs();
                        txtCNAECod.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
                        txtCNAEDesc.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
                    }
                    
                    setTitle("Cadastro de CNAE - " + statusFrame);

                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Ocorreu Um Erro ao Incluir o Novo CNAE! Nenhum registro Foi Incluído! \n" + ex.getMessage());
                }
            }

        }
        
        else if(statusFrame == statusFrame.Editando){
            Connection cn = DAO.getConexao();
                try {
                    PreparedStatement pstm = cn.prepareStatement("UPDATE cnae SET codigo=?,descCNAE=? WHERE codigo ="+ jTable1.getValueAt(jTable1.getSelectedRow(), 0));
                    pstm.setInt(1, Integer.parseInt(txtCNAECod.getText().trim()));
                    pstm.setString(2, txtCNAEDesc.getText().trim());
                    int retorno = pstm.executeUpdate();
                    
                    if(retorno <= 0){
                        JOptionPane.showMessageDialog(null, "Não Foi Possível Atualizar o Registro!");
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Registro Atualizado com Sucesso!");
                        carregaTabelaCNAEs();
                        statusFrame = statusFrame.Navegando;
                        ManipulaComponentes.gerenciaBotoes(botoes, statusFrame);
                    }
                    
                } catch (SQLException ex) {
                    Logger.getLogger(frmCadastrarCNAE.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed

       JOptionPane.showMessageDialog(null,  jTable1.getSelectedRow());
       
       
       if(jTable1.getSelectedRow() < 0){
           JOptionPane.showMessageDialog(null, "Selecione um Registro na Tabela para Excluir!");
       }
       else{
           if (JOptionPane.showConfirmDialog(null, "Confirma a Exclusão Permanente do Registro?", "Exclusão", JOptionPane.YES_NO_OPTION) == 0) {
            
            if (model.excluir(jTable1.getSelectedRow(), 0) <= 0) {
                JOptionPane.showMessageDialog(null, "Não Foi Possível Excluir o Registro!");
            } else {
                JOptionPane.showMessageDialog(null, "Registro Excluído com Sucesso!");

                carregaTabelaCNAEs();
            }
        }
       }
    
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
      
        if(statusFrame == statusFrame.Navegando){
            //Verificar se há um registro selecionado no Grid
            if(jTable1.getSelectedRow() < 0){
                JOptionPane.showMessageDialog(null, "Selecione um Registro na Tabela Abaixo!");
            }
            else{
                linhaParaEdicao = jTable1.getSelectedRow();
                statusFrame = statusFrame.Editando;
                ManipulaComponentes.gerenciaBotoes(botoes, statusFrame);
                setTitle("Cadastro de CNAE - " + statusFrame);
            }
        }
        else if(statusFrame == statusFrame.Editando || statusFrame == statusFrame.Adicionando){
            
            if(JOptionPane.showConfirmDialog(null, "Você está "+ statusFrame + " um registro. Deseja Abandona a operação?", "Edição de Registro", JOptionPane.YES_NO_OPTION) == 0){
                statusFrame = statusFrame.Navegando;
                setTitle("Cadastro de CNAE - " + statusFrame);
                ManipulaComponentes.gerenciaBotoes(botoes, statusFrame);
                txtCNAECod.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
                txtCNAEDesc.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
            }
        }
        
    }//GEN-LAST:event_btnEditActionPerformed

    public void carregaTabelaCNAEs() {

        model.limpar();
        jTable1.removeAll();
        Connection cn = DAO.getConexao();
        String consultaCNAE = "SELECT codigo, descCNAE FROM CNAE ORDER BY descCNAE";
        try {
            PreparedStatement pstm1 = cn.prepareStatement(consultaCNAE);
            ResultSet rsCNAEs = pstm1.executeQuery();
            int contador = 0;
            while (rsCNAEs.next()) {
                jTable1.setRowHeight(30);
                CNAE cnae = new CNAE();
                cnae.setCnae(rsCNAEs.getInt("codigo"));
                cnae.setCnaeDescricao(rsCNAEs.getString("descCNAE"));
                model.inserir(cnae);
                contador++;

            }

            jLabel3.setText("" + contador);
        } catch (SQLException ex) {

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCadastrarCNAE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCadastrarCNAE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCadastrarCNAE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCadastrarCNAE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmCadastrarCNAE dialog = new frmCadastrarCNAE(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDispose;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRemove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCNAECod;
    private javax.swing.JTextField txtCNAEDesc;
    // End of variables declaration//GEN-END:variables
}
