/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Formularios;

import Formularios.Configuracoes.Padronizacoes.frmPadronizacoesDeCadastros;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Joanes Gonzaga
 */
public class frmMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmMenuPrincipal
     */
    public frmMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuConfiguracoes = new javax.swing.JMenu();
        mitemAcessoBanco = new javax.swing.JMenuItem();
        subMenuPadronizacoes = new javax.swing.JMenu();
        mitemDefinicoes = new javax.swing.JMenuItem();
        mitemSair = new javax.swing.JMenuItem();
        menuOS = new javax.swing.JMenu();
        mitemAtendimento = new javax.swing.JMenuItem();
        mmitemExecutarOS = new javax.swing.JMenuItem();
        menuCadastros = new javax.swing.JMenu();
        mitemCadastrarClientes = new javax.swing.JMenuItem();
        jmnuAuxiliares = new javax.swing.JMenu();
        mItemCNAE = new javax.swing.JMenuItem();
        mItemCEP = new javax.swing.JMenuItem();
        menuPesquisas = new javax.swing.JMenu();
        mitemPesquisarClientes = new javax.swing.JMenuItem();
        mitemPesquisarOS = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ordem de Serviços - Softaway Sistemas");
        setExtendedState(6);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jLabel1, gridBagConstraints);

        jMenuBar1.setPreferredSize(new java.awt.Dimension(259, 40));

        menuConfiguracoes.setText("Configurações ");

        mitemAcessoBanco.setText("Acesso ao BD");
        menuConfiguracoes.add(mitemAcessoBanco);

        subMenuPadronizacoes.setText("Padronizações do Sistema");

        mitemDefinicoes.setText("Definições para Clientes");
        mitemDefinicoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemDefinicoesActionPerformed(evt);
            }
        });
        subMenuPadronizacoes.add(mitemDefinicoes);

        menuConfiguracoes.add(subMenuPadronizacoes);

        mitemSair.setText("Sair");
        mitemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemSairActionPerformed(evt);
            }
        });
        menuConfiguracoes.add(mitemSair);

        jMenuBar1.add(menuConfiguracoes);

        menuOS.setText("Ordem de Serviços");

        mitemAtendimento.setText("Atendimento");
        mitemAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemAtendimentoActionPerformed(evt);
            }
        });
        menuOS.add(mitemAtendimento);

        mmitemExecutarOS.setText("Ordem de Serviço - Execução");
        mmitemExecutarOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmitemExecutarOSActionPerformed(evt);
            }
        });
        menuOS.add(mmitemExecutarOS);

        jMenuBar1.add(menuOS);

        menuCadastros.setText("Cadastros ");

        mitemCadastrarClientes.setText("Cadastrar Clientes");
        mitemCadastrarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemCadastrarClientesActionPerformed(evt);
            }
        });
        menuCadastros.add(mitemCadastrarClientes);

        jmnuAuxiliares.setText("Auxiliares");

        mItemCNAE.setText("Cadastro de CNAE");
        mItemCNAE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemCNAEActionPerformed(evt);
            }
        });
        jmnuAuxiliares.add(mItemCNAE);

        mItemCEP.setText("Manutenção de CEPs");
        mItemCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemCEPActionPerformed(evt);
            }
        });
        jmnuAuxiliares.add(mItemCEP);

        menuCadastros.add(jmnuAuxiliares);

        jMenuBar1.add(menuCadastros);

        menuPesquisas.setText("Consultas ");

        mitemPesquisarClientes.setText("Consultar Clientes");
        mitemPesquisarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemPesquisarClientesActionPerformed(evt);
            }
        });
        menuPesquisas.add(mitemPesquisarClientes);

        mitemPesquisarOS.setText("Consultar Ordens de Serviço");
        mitemPesquisarOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemPesquisarOSActionPerformed(evt);
            }
        });
        menuPesquisas.add(mitemPesquisarOS);

        jMenuBar1.add(menuPesquisas);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mitemAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemAtendimentoActionPerformed
    
        frmAtendimento atendimento = new frmAtendimento();
        atendimento.setVisible(true);
    }//GEN-LAST:event_mitemAtendimentoActionPerformed

    private void mmitemExecutarOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmitemExecutarOSActionPerformed
           frmOSExecucao execucaoOS = new frmOSExecucao();
           execucaoOS.setVisible(true);
    }//GEN-LAST:event_mmitemExecutarOSActionPerformed

    private void mitemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mitemSairActionPerformed

    private void mitemPesquisarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemPesquisarClientesActionPerformed
       
        frmLocalizaPessoas buscarPessoas = new frmLocalizaPessoas();       
        buscarPessoas.setVisible(true);
    }//GEN-LAST:event_mitemPesquisarClientesActionPerformed

    private void mitemCadastrarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemCadastrarClientesActionPerformed
        
        frmCadastrarClientes cadastraClientes = new frmCadastrarClientes();
        cadastraClientes.setVisible(true);
    }//GEN-LAST:event_mitemCadastrarClientesActionPerformed

    private void mitemPesquisarOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemPesquisarOSActionPerformed
        
        frmConsultarOS consultarOS = new frmConsultarOS();
        consultarOS.setVisible(true);
    }//GEN-LAST:event_mitemPesquisarOSActionPerformed

    private void mitemDefinicoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemDefinicoesActionPerformed
        
        Formularios.Configuracoes.Padronizacoes.frmPadronizacoesDeCadastros cadastros = new frmPadronizacoesDeCadastros();
        
        cadastros.setVisible(true);
    }//GEN-LAST:event_mitemDefinicoesActionPerformed

    private void mItemCNAEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemCNAEActionPerformed
       frmCadastrarCNAE cnaes = new frmCadastrarCNAE(null, false);
       cnaes.setVisible(true);
    }//GEN-LAST:event_mItemCNAEActionPerformed

    private void mItemCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemCEPActionPerformed
        frmCadastroCEP ceps = new frmCadastroCEP();
        
        ceps.setVisible(true);
    }//GEN-LAST:event_mItemCEPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        /*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        */
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmnuAuxiliares;
    private javax.swing.JMenuItem mItemCEP;
    private javax.swing.JMenuItem mItemCNAE;
    private javax.swing.JMenu menuCadastros;
    private javax.swing.JMenu menuConfiguracoes;
    private javax.swing.JMenu menuOS;
    private javax.swing.JMenu menuPesquisas;
    private javax.swing.JMenuItem mitemAcessoBanco;
    private javax.swing.JMenuItem mitemAtendimento;
    private javax.swing.JMenuItem mitemCadastrarClientes;
    private javax.swing.JMenuItem mitemDefinicoes;
    private javax.swing.JMenuItem mitemPesquisarClientes;
    private javax.swing.JMenuItem mitemPesquisarOS;
    private javax.swing.JMenuItem mitemSair;
    private javax.swing.JMenuItem mmitemExecutarOS;
    private javax.swing.JMenu subMenuPadronizacoes;
    // End of variables declaration//GEN-END:variables
}
